apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfghsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfghsf
  template:
    metadata:
      labels:
        app: nfghsf
    spec:
      containers:
      - image: okteto.dev/nfghsf:latest
        name: nfghsf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "cbe78924-4d50-4840-91be-ea37df52c54a"
        - name: Vless_Path
          value: "/vl623556"
        - name: Vmess_UUID
          value: "cbe78924-4d50-4840-91be-ea37df52c54a"
        - name: Vmess_Path
          value: "/vm9765we"
        - name: Share_Path
          value: "/v2link"
